apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-sn
  title: test-sn
  description: Pepsico CMP Flow for Approval - Create ServiceNow Ticket
  tags:
    - service-now
    - pepsico
    - cloud-market-place
spec:
  owner: rhdh
  type: service
  

  parameters:
    - title: Provide Name Entry for snow table 
      required:
        - employeename
      properties:
        employeename:
          title: Requester Name
          type: string  
        department:
          title: Requester's Department
          type: string  
        project:
          title: Requester's Project
          type: string  
  steps:
    - id: snowcreate
      name: Snow
      action: servicenow:now:table:createRecord
      input:
        tableName: x_1520818_pepsico_pepsionboarding
        requestBody: {
          application_owner: "${{ parameters.employeename }}",
          project_sector: "${{ parameters.department }}",
          application_name: "${{ parameters.project }}"
        }
        
  output:
    text:
    - title: Name Field
      content: Entered Name "${{ parameters.employeename }}"
    - title: SysID
      content: Create record with this System ID "${{ steps.snowcreate.output.result.sys_id }}"
